#!/bin/sh /etc/rc.common

START=18

USE_PROCD=1
NAME=supervisord
PROG=/usr/bin/supervisord
CONFIG=/etc/supervisord.conf

start_service() {
	procd_open_instance
        procd_set_param command "$PROG" -c $CONFIG
	procd_close_instance
}
