#!/bin/sh /etc/rc.common
#
# AUTHOR: Takumi Sueda <puhitaku@gmail.com>
#
# Start/stop/restart supervisor in OpenWrt.

START=91

USE_PROCD=1
PROCD_DEBUG=1
PROG=/usr/bin/supervisord

DAEMON=${PROG}

# Location of the pid file
PIDFILE=/tmp/supervisord.pid

# Config of supervisor
CONFIG=/etc/supervisord.conf

start_service()
{
    # $DAEMON -c $CONFIG -j $PIDFILE
    procd_open_instance
    echo hhhhh
    procd_set_param command $PROG -c $CONFIG -j $PIDFILE
    procd_set_param respawn
    procd_close_instance
    touch $CONFIG
}

stop_service()
{
    kill $(cat $PIDFILE)
}

service_triggers()
{
        procd_add_reload_trigger "uci-file-name"
}
